import { NextRequest, NextResponse } from "next/server";
import { getJob, logActivity } from "@/lib/db";
import { generateCoverLetter } from "@/lib/agent";

export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const jobId = Number(id);

  try {
    const job = getJob(jobId);
    if (!job) return NextResponse.json({ error: "Job not found" }, { status: 404 });

    const result = await generateCoverLetter({
      jobId,
      company: job.company,
      title: job.title,
      description: job.description,
      jobLink: job.job_link,
    });

    if (result.success) {
      logActivity(jobId, "cover_letter_generated", "Cover letter generated by AI agent");
      return NextResponse.json({ success: true, agentId: result.agentId });
    } else {
      return NextResponse.json({ success: false, error: result.error }, { status: 500 });
    }
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
